proxy_server: 
  address: localhost:8080

backend_servers:
  - http://localhost:2000
  - http://localhost:3000
  - http://localhost:4000

worker_processes: 4

routing:
  strategy: round_robin

health_check:
  enabled: true
  timeout: 0           # 0 to disable timeout
  interval: 5          # Interval in seconds for regular health checks
  max_backoff: 60      # Maximum backoff time in seconds for retrying failed servers
  initial_backoff: 2.0 # Initial backoff interval in seconds, allowing float values

logging:
  level: "DEBUG"
  file: "/tmp/balancer.log"
