server_pool:
  - http://localhost:2000
  - http://localhost:3000
  - http://localhost:4000

worker_processes: 4
listen_port: 8080

routing:
  strategy: round_robin

health_check:
  enabled: true
  interval: 2
  timeout: 4

logging:
  level: "DEBUG"
  file: "/tmp/balancer.log"
