services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "2000:5000"  

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3000:5000"  

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "4000:5000"  
